ROLE_ADMIN = "admin"
ROLE_ANALYST = "analyst"

TASK_STATUS_DRAFT = "draft"
TASK_STATUS_READY = "ready"
TASK_STATUS_QUEUED = "queued"
TASK_STATUS_PARSING = "parsing"
TASK_STATUS_EXTRACTING = "extracting"
TASK_STATUS_DETECTING_CONFLICTS = "detecting_conflicts"
TASK_STATUS_GENERATING_REPORT = "generating_report"
TASK_STATUS_AWAITING_REVIEW = "awaiting_review"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

TASK_RUNNING_STATUSES = {
    TASK_STATUS_QUEUED,
    TASK_STATUS_PARSING,
    TASK_STATUS_EXTRACTING,
    TASK_STATUS_DETECTING_CONFLICTS,
    TASK_STATUS_GENERATING_REPORT,
}

FILE_STATUS_UPLOADED = "uploaded"
FILE_STATUS_PARSING = "parsing"
FILE_STATUS_PARSED = "parsed"
FILE_STATUS_WARNING = "warning"
FILE_STATUS_FAILED = "failed"

RUN_STATUS_QUEUED = "queued"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_SUCCEEDED = "succeeded"
RUN_STATUS_FAILED = "failed"

CONFLICT_STATUS_UNREVIEWED = "unreviewed"
CONFLICT_STATUS_CONFIRMED = "confirmed"
CONFLICT_STATUS_IGNORED = "ignored"

SKILL_STATUS_UNKNOWN = "unknown"
SKILL_STATUS_HEALTHY = "healthy"
SKILL_STATUS_ERROR = "error"
